### ISSUE TITLE
Build failing due to failed bootstrap

### ISSUE THREAD

**Issue by japantreepot** [scallyw4g/poof#8]
The build script assumes `./bin/poof` exists and deletes the `generated` directory, which is required to build `./bin/poof` the first time.

https://github.com/scallyw4g/poof/blob/def576952381dc49b5d42292a30d3fb73a6fde96/make.sh#L167-L171

**Comment by scallyw4g** [comment]
Hmmmmm, good catch.  I'll have to take a look at how to handle this.  Next time I carve out some time for working on these projects I'm going to set up CI/CD for all of them, at which time I can take care of this too.
